#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 26 09:48:59 2021

@author: sam
"""

import subprocess as sbp
import os

path='/home/sam/Downloads/CMFD'
fol = os.listdir(path)
print(fol)
p2 = '/home/sam/Downloads/Combo'

for i in fol:
    p1 = os.path.join(path,i)
    fol2 = os.listdir(p1)
    for j in fol2:
        pj = os.path.join(p1,j)
        p2j = p2 + '/' + j
        p3 = 'cp -r ' + pj +' ' + p2j
        sbp.Popen(p3,shell=True)
    print(p3)